name: Receive

on:
  workflow_dispatch:
    inputs:
      product_version:
        description: "Product Version (e.g. x.x.x)"
        required: true
  repository_dispatch:
    types: [product_fetch]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        run: |
          ENV=${{ github.event.client_payload.product_version }}
          echo "ENV = $ENV"
