name: Receive

on:
  workflow_dispatch:
    inputs:
      product_version:
        description: "Product Version (e.g. x.x.x)"
        required: true
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        run: |
          env=${{ github.event.client_payload.env }}
          echo "ENV = $env"
