name: Receive

on:
  workflow_dispatch:
    inputs:
      product_version:
        description: "Product Version (e.g. x.x.x)"
        required: true
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        run: |
          PRODUCT_VERSION_ENV=${{ github.event.client_payload.product_version }}
          echo "PRODUCT_VERSION_ENV = $PRODUCT_VERSION_ENV"
